### ISSUE TITLE
 (Postgrex.QueryError) type `ltree` can not be handled by the types module Postgrex.DefaultTypes

### ISSUE THREAD

**Issue by glennr** [jwilger/dagex#4]
Hi!

I'm getting this error with `all_paths/2`:

```
> Step.all_paths(trigger, loop) |> Repo.all
[debug] QUERY ERROR source="dagex_paths" db=0.0ms queue=18.8ms idle=1053.3ms
SELECT d0."path", f3."nr", s5."id", s5."name", s5."inserted_at", s5."updated_at" FROM "dagex_paths" AS d0 INNER JOIN "dagex_nodes" AS d1 ON d1."id" = d0."node_id" INNER JOIN "dagex_nodes" AS d2 ON d0."path" ~ CAST('*.' || d2."id" || '.*' AS lquery) LEFT OUTER JOIN LATERAL (SELECT a.elem, a.nr FROM unnest(string_to_array(d0."path"::text, '.')::int[]) WITH ORDINALITY AS a(elem, nr)) AS f3 ON TRUE INNER JOIN "dagex_nodes" AS d4 ON d4."id" = f3."elem" INNER JOIN "steps" AS s5 ON s5."id"::text = d4."ext_id" WHERE ((((d1."ext_id" = $1::text) AND (d1."node_type" = $2)) AND (d2."ext_id" = $3::text)) AND (d2."node_type" = $4)) ORDER BY d0."path", f3."nr" ["5", "steps", "3", "steps"]
** (Postgrex.QueryError) type `ltree` can not be handled by the types module Postgrex.DefaultTypes
    (ecto_sql 3.9.2) lib/ecto/adapters/sql.ex:913: Ecto.Adapters.SQL.raise_sql_call_error/1
    (ecto_sql 3.9.2) lib/ecto/adapters/sql.ex:828: Ecto.Adapters.SQL.execute/6
    (ecto 3.9.4) lib/ecto/repo/queryable.ex:229: Ecto.Repo.Queryable.execute/4
    (ecto 3.9.4) lib/ecto/repo/queryable.ex:19: Ecto.Repo.Queryable.all/3
    iex:18: (file)
```

EDIT:  I see in the docs I should be using `dagex_paths` and not `all`, but`Step.all_paths(trigger, loop) |> Repo.dagex_paths()` yields the same error.

This is the test script I used (following the example in the README):

````
alias Brmbl.Step
alias Brmbl.Repo
{:ok, trigger} = %Step{name: "trigger"} |> Repo.insert()
{:ok, csv} = %Step{name: "csv-1"} |> Repo.insert()
{:edge_created, _edge} = Step.create_edge(trigger, csv) |> Repo.dagex_update()
{:ok, loop} = %Step{name: "loop-1"} |> Repo.insert()
{:edge_created, _edge} = Step.create_edge(csv, loop) |> Repo.dagex_update()
{:ok, transform} = %Step{name: "transform-1"} |> Repo.insert()
{:edge_created, _edge} = Step.create_edge(loop, transform) |> Repo.dagex_update()
```


With these migrations:

```
index 000000000..c8f03b989
--- /dev/null
+++ b/priv/repo/migrations/20230411054258_add_dagex_to_project.exs
@@ -0,0 +1,11 @@
+defmodule Brmbl.Repo.Migrations.AddDagexToProject do
+  use Ecto.Migration
+
+  def up do
+    Dagex.Migrations.up()
+  end
+
+  def down do
+    Dagex.Migrations.down()
+  end
+end
diff --git a/priv/repo/migrations/20230411054356_add_steps.exs b/priv/repo/migrations/20230411054356_add_step
s.exs
new file mode 100644
index 000000000..ea4b7bdf4
--- /dev/null
+++ b/priv/repo/migrations/20230411054356_add_steps.exs
@@ -0,0 +1,16 @@
+defmodule Brmbl.Repo.Migrations.AddSteps do
+  require Dagex.Migrations
+
+  use Ecto.Migration
+
+  def change do
+    create table("steps") do
+      add(:name, :string, null: false)
+      timestamps()
+    end
+
+    # Adds triggers to the "organizations" table to maintain the associated DAG as
+    # records are added/removed.
+    Dagex.Migrations.setup_node_type("steps", "3.0.0")
+  end
+end
```

My mix.lock looks like this:

````
+      {:dagex, "~> 3.0"},
````

which gave these changes to mix.lock

```
+  "dagex": {:hex, :dagex, "3.0.1", "0cdc957e65e07a324a30ed450cb36e6bdeb2fec72bfe34954b1d4554226d4b79", [:mix], [{:ecto_ltree, "~> 0.3.0", [hex: :ecto_ltree, repo: "hexpm", optional: false]}, {:ecto_sql, "~> 3.6", [hex: :ecto_sql, repo: "hexpm", optional: false]}, {:jason, "~> 1.0", [hex: :jason, repo: "hexpm", optional: false]}, {:postgrex, ">= 0.0.0", [hex: :postgrex, repo: "hexpm", optional: false]}, {:typed_ecto_schema, "~> 0.3", [hex: :typed_ecto_schema, repo: "hexpm", optional: false]}], "hexpm", "0db799b684ec184cff09e60e54d2698714d2c2e52a9da13b0b33ebd91c71ab97"},
+  "ecto_ltree": {:hex, :ecto_ltree, "0.3.0", "280b35149d506ac4de06cb87dbfcb56b52d111598b5b95fbd806ee3a6f73caf7", [:mix], [{:ecto, "~> 3.2", [hex: :ecto, repo: "hexpm", optional: false]}, {:postgrex, ">= 0.0.0", [hex: :postgrex, repo: "hexpm", optional: false]}], "hexpm", "9379b3e2ea1e9e259ce7c15487aeeee688486ecdba3d650d923ea5b96bd10472"},
+  "typed_ecto_schema": {:hex, :typed_ecto_schema, "0.4.1", "a373ca6f693f4de84cde474a67467a9cb9051a8a7f3f615f1e23dc74b75237fa", [:mix], [{:ecto, "~> 3.5", [hex: :ecto, repo: "hexpm", optional: false]}], "hexpm", "85c6962f79d35bf543dd5659c6adc340fd2480cacc6f25d2cc2933ea6e8fcb3b"},
```

And `mix deps.get` reported this:

```
New:
  dagex 3.0.1
  ecto_ltree 0.3.0
  typed_ecto_schema 0.4.1
* Updating briefly (Hex package)
* Getting dagex (Hex package)
* Updating phoenix (Hex package)
* Updating phoenix_live_view (Hex package)
* Updating phoenix_storybook (Hex package)
* Updating plug_cowboy (Hex package)
* Updating plug_crypto (Hex package)
* Updating prom_ex (Hex package)
* Getting sweet_xml (Hex package)
* Updating finch (Hex package)
* Updating octo_fetch (Hex package)
* Updating mint (Hex package)
* Updating nimble_options (Hex package)
* Updating plug (Hex package)
* Updating earmark (Hex package)
* Updating earmark_parser (Hex package)
* Updating websock_adapter (Hex package)
* Updating websock (Hex package)
* Getting ecto_ltree (Hex package)
* Getting typed_ecto_schema (Hex package)
```

The project is running these versions:
- elixir 1.14.2-otp-25
- erlang 25.2
- postgres:14.7

**Comment by glennr** [comment]
This appears to be the solution: https://github.com/josemrb/ecto_ltree#2-define-a-type-module-with-our-custom-extensions


```
diff --git a/config/config.exs b/config/config.exs
index 073552caf..70440bb8e 100644
--- a/config/config.exs
+++ b/config/config.exs
@@ -10,7 +10,9 @@ config :brmbl, ecto_repos: [Brmbl.Repo], env: Mix.env()
 
 # Our ranges are all tstzrange, so for consistency lets use the same types in
 # all timestamp fields
-config :brmbl, Brmbl.Repo, migration_timestamps: [type: :timestamptz]
+config :brmbl, Brmbl.Repo,
+  migration_timestamps: [type: :timestamptz],
+  types: Brmbl.PostgresTypes
```

```
% cat lib/postgrex_types.ex
Postgrex.Types.define(
  Brmbl.PostgresTypes,
  [EctoLtree.Postgrex.Lquery, EctoLtree.Postgrex.Ltree] ++ Ecto.Adapters.Postgres.extensions()
)
```

I think it would be helpul if these steps were added to the README for this project
